version: "3.8"

services:
  postgres1:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5433:5432"
    networks:
      intranet1:
        ipv4_address: 10.10.1.2

  postgres2:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase2"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5434:5432"
    networks:
      intranet2:
        ipv4_address: 10.10.2.2

  postgres3:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase3"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5435:5432"
    networks:
      intranet3:
        ipv4_address: 10.10.3.2

  rabbitmq:
    image: rabbitmq:management
    environment:
      - "RABBITMQ_DEFAULT_PASS=secret"
      - "RABBITMQ_DEFAULT_USER=myuser"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internet
      - intranet_geral

networks:
  internet:
    driver: bridge

  intranet_geral:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.0.0/24"

  intranet1:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.1.0/24"

  intranet2:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.2.0/24"

  intranet3:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.3.0/24"
