# Usa a imagem base do OpenJDK 21
FROM openjdk:21-jdk-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo JAR da aplicação para dentro do contêiner
COPY target/*.jar app.jar

# Expõe a porta padrão da aplicação Spring Boot (8080)
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["java", "-jar", "app.jar"]
