FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /home/app

COPY . .

RUN chmod +x ./gradlew

RUN ./gradlew clean build -x test

FROM eclipse-temurin:21-jre-alpine

WORKDIR /home/app

EXPOSE 8080

COPY --from=builder /home/app/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
